import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Innovation from '../components/Innovative'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Buildit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main  className=''>
        <Hero/>
        <Innovation/>
      </main>

      
    </div>
  )
}
