import Head from 'next/head'
import Image from 'next/image'
import Contact from '../components/Contact'
import Hero from '../components/Hero'
import Innovation from '../components/Innovative'
import Aboutus from '../components/Aboutus'
import Properties from '../components/Properties'
import Socials from '../components/Socials'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Buildit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main  className=''>
        <Hero/>
        <Innovation/>
        <Aboutus/>
        <Properties/>
        <Socials/>
        <Contact/>
      </main>

      
    </div>
  )
}
